version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80" # 外部访问端口
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf:ro # 挂载 Nginx 配置
    depends_on:
      - web
      - server
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    # 不再需要映射端口，Nginx 会处理
    # ports:
    #   - "3000:3000"
    networks:
      - app-network
    # 可以添加环境变量，例如 API 地址
    # environment:
    #   - NEXT_PUBLIC_API_URL=/api

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    # ports:
    #   - "3001:3001" # 端口由内部网络访问，无需映射到宿主机
    # environment:
    #   - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    networks:
      - app-network

  # Add a database service if required
  # db:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network
  #   ports:
  #     - "5432:5432"

networks:
  app-network:
    driver: bridge
# volumes:
#   postgres_data: # Define the volume for database persistence
